/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import DatabaseRetrieve.NewsStory;
import apiCalls.NewsConnection;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author jodic
 */
public class NewsPanel extends javax.swing.JPanel {
    /**
     * Creates new form NewsPanel
     */
    JLabel[] stories;
      ArrayList<NewsStory> c;
    public NewsPanel() {
        initComponents();
        stories = new JLabel[]{jlStoryOne, jlStoryTwo, jlStoryThree};
    }   
    public String getTopicname(){
        return jlTitle.getText();
    }
    public void setValues(NewsConnection newCon){
        jlTitle.setText(newCon.getSection());
       c= newCon.getStories();
        for(int i=0; i<c.size(); i++){
            if(c.get(i).getTitle().length()>79){
           String title = c.get(i).getTitle().substring(0, 75)+"...";
            stories[i].setText(title);
            }
            else{
        stories[i].setText(c.get(i).getTitle());
            }
        }
    }
    //Use of opening a link into default browser
    //https://gist.github.com/GiriB/b79f47e4d970dec887a7
    public void openStory(String storylink){
        java.awt.Desktop d = java.awt.Desktop.getDesktop();
        try{
            URI link = new URI(storylink);
            d.browse(link);
        } catch (URISyntaxException ex) {
            Logger.getLogger(NewsPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NewsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitle = new javax.swing.JLabel();
        jlStoryOne = new javax.swing.JLabel();
        jlStoryTwo = new javax.swing.JLabel();
        jlStoryThree = new javax.swing.JLabel();

        jlTitle.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jlTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlStoryOne.setBackground(new java.awt.Color(51, 51, 51));
        jlStoryOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlStoryOne.setOpaque(true);
        jlStoryOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlStoryOneMouseClicked(evt);
            }
        });

        jlStoryTwo.setBackground(new java.awt.Color(51, 51, 51));
        jlStoryTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlStoryTwo.setOpaque(true);
        jlStoryTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlStoryTwoMouseClicked(evt);
            }
        });

        jlStoryThree.setBackground(new java.awt.Color(51, 51, 51));
        jlStoryThree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlStoryThree.setOpaque(true);
        jlStoryThree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlStoryThreeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlStoryTwo, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(jlStoryOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlStoryThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlStoryOne, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlStoryTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlStoryThree, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jlStoryOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlStoryOneMouseClicked
        String storylink1 = c.get(0).getStorylink();
        this.openStory(storylink1);
    }//GEN-LAST:event_jlStoryOneMouseClicked

    private void jlStoryTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlStoryTwoMouseClicked
        String storylink2 = c.get(1).getStorylink();
        this.openStory(storylink2);
    }//GEN-LAST:event_jlStoryTwoMouseClicked

    private void jlStoryThreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlStoryThreeMouseClicked
        String storylink3 = c.get(2).getStorylink();
        this.openStory(storylink3);
    }//GEN-LAST:event_jlStoryThreeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlStoryOne;
    private javax.swing.JLabel jlStoryThree;
    private javax.swing.JLabel jlStoryTwo;
    private javax.swing.JLabel jlTitle;
    // End of variables declaration//GEN-END:variables
}
