/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import DatabaseRetrieve.NewsStory;
import api.NewsConnection;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author jodic
 */
public class NewsPanel extends javax.swing.JPanel {
    /**
     * Creates new form NewsPanel
     */
    JLabel[] stories;
      ArrayList<NewsStory> c;
    public NewsPanel() {
        initComponents();
        stories = new JLabel[]{jlStoryOne, jlStoryTwo, jlStoryThree};
    }   
    public String getTopicname(){
        return jlTitle.getText();
    }
    public void setValues(NewsConnection newCon){
        jlTitle.setText("Topic:"+newCon.getSection());
       c= newCon.getStories();
        for(int i=0; i<c.size(); i++){
        stories[i].setText(c.get(i).getTitle());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitle = new javax.swing.JLabel();
        jlStoryOne = new javax.swing.JLabel();
        jlStoryTwo = new javax.swing.JLabel();
        jlStoryThree = new javax.swing.JLabel();

        jlTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlStoryOne.setBackground(new java.awt.Color(51, 51, 51));
        jlStoryOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlStoryOne.setOpaque(true);
        jlStoryOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlStoryOneMouseClicked(evt);
            }
        });

        jlStoryTwo.setBackground(new java.awt.Color(51, 51, 51));
        jlStoryTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlStoryTwo.setOpaque(true);
        jlStoryTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlStoryTwoMouseClicked(evt);
            }
        });

        jlStoryThree.setBackground(new java.awt.Color(51, 51, 51));
        jlStoryThree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlStoryThree.setOpaque(true);
        jlStoryThree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlStoryThreeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlStoryTwo, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(jlStoryOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlStoryThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlStoryOne, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlStoryTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlStoryThree, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jlStoryOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlStoryOneMouseClicked
        System.out.print(stories[0].getText());
        System.out.println(c.get(0).getStorylink());
    }//GEN-LAST:event_jlStoryOneMouseClicked

    private void jlStoryTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlStoryTwoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlStoryTwoMouseClicked

    private void jlStoryThreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlStoryThreeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlStoryThreeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlStoryOne;
    private javax.swing.JLabel jlStoryThree;
    private javax.swing.JLabel jlStoryTwo;
    private javax.swing.JLabel jlTitle;
    // End of variables declaration//GEN-END:variables
}
