/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustomRenders;

import api.StockConnection;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author jodic
 */
public class StocksListRender extends javax.swing.JPanel implements ListCellRenderer<StockConnection>{

    /**
     * Creates new form StocksListRender
     */
    public StocksListRender() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblStockName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblStockHigh = new javax.swing.JLabel();
        lblStockLow = new javax.swing.JLabel();
        lblStockOpen = new javax.swing.JLabel();
        lblStockClose = new javax.swing.JLabel();

        jlblStockName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblStockName.setText("jLabel1");

        jLabel1.setText("High:");

        jLabel2.setText("Low:");

        jLabel3.setText("Open:");

        jLabel4.setText("Close:");

        lblStockHigh.setText("$$.00");

        lblStockLow.setText("$$.00");

        lblStockOpen.setText("$$.00");

        lblStockClose.setText("$$.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblStockName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblStockOpen))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblStockHigh)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStockClose)
                            .addComponent(lblStockLow))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblStockName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lblStockHigh)
                    .addComponent(lblStockLow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(lblStockOpen)
                    .addComponent(lblStockClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
  @Override
    public Component getListCellRendererComponent(JList<? extends StockConnection> list, StockConnection value, int index, boolean isSelected, boolean cellHasFocus) {
        this.setOpaque(true);
        jlblStockName.setText(value.getSymb());
        lblStockHigh.setText(""+value.getHigh());
        lblStockLow.setText(""+value.getLow());
        lblStockClose.setText(""+value.getClose());
        lblStockOpen.setText(""+value.getOpen());
        if(isSelected){
            setBackground(Color.blue);
        }
        else{
            setBackground(list.getBackground());
        }
        return this;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jlblStockName;
    private javax.swing.JLabel lblStockClose;
    private javax.swing.JLabel lblStockHigh;
    private javax.swing.JLabel lblStockLow;
    private javax.swing.JLabel lblStockOpen;
    // End of variables declaration//GEN-END:variables

  
}
