/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboards;

import RegisterWindows.StartScreen;
import UserInfo.CustomUser;
import apiCalls.CovidConnection;
import apiCalls.TimeApi;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author jodic
 */
public class DashBoardControlPanel extends javax.swing.JFrame{
    private TimeApi timeApiCall;
    private CovidDashboard cd;
    private NewsDashboard nd;
    private StocksDashboard sd;
    private CustomUser cu;
    private Timer t;
    /**
     * Creates new form DashBoardControlPanel
     */
    public DashBoardControlPanel() {
        initComponents();
        
        //thread for timeApiCall
            //within thread a timer that updates the timeApiCall every 30 sec
         this.cd = new CovidDashboard(new CovidConnection("Massachusetts"));
            cd.setVisible(true);
            cd.setLocationRelativeTo(this);
    }
    public DashBoardControlPanel(CustomUser cu){
        this.cu = cu;
        initComponents();
        timeApiCall = new TimeApi();
        jlLoaded.setText("Last Loaded:"+timeApiCall.getDate()+" @"+timeApiCall.getTime());
        
        this.setLocationRelativeTo(null);
        if(cu.isCovid()){
            //this.cd = new CovidDashboard(cu.getCovidinfo());
            this.cd = new CovidDashboard(cu.getCovidinfo());
            cd.setVisible(true);
            cd.setLocationRelativeTo(this);
        }
        if(cu.isStocks()){
            this.sd = new StocksDashboard(cu.getStocks());
            sd.setVisible(true);
        }
        if(cu.isNews()){
            this.nd = new NewsDashboard(cu.getNews());
            nd.setVisible(true);
        }
        if(cu.isWeather()){
            //add the weather part of the api
        }
    }
    public void hideWins(){
            if(cu.isStocks()){
        sd.setVisible(false);
        }
        if(cu.isCovid()){
        cd.setVisible(false);
        }
        if(cu.isNews()){
        nd.setVisible(false);
        }
    this.setTitle("Dashboard control panel");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jlLoaded = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmtoMain = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jmCovidWin = new javax.swing.JMenuItem();
        jmNewsWin = new javax.swing.JMenuItem();
        jmStocksWin = new javax.swing.JMenuItem();
        jmHide = new javax.swing.JMenuItem();
        jmShow = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(306, 131));
        setMinimumSize(new java.awt.Dimension(306, 131));

        jButton1.setText("Sign-out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back to Main Menu");

        jlLoaded.setText("Last Loaded:");

        jmtoMain.setText("File");

        jMenuItem5.setText("Return to Start Page");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jmtoMain.add(jMenuItem5);

        jMenuBar1.add(jmtoMain);

        jMenu2.setText("View");

        jMenu3.setText("Toggle  Specific Window");

        jmCovidWin.setText("Covid Window");
        jmCovidWin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCovidWinActionPerformed(evt);
            }
        });
        jMenu3.add(jmCovidWin);

        jmNewsWin.setText("News Window");
        jmNewsWin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmNewsWinActionPerformed(evt);
            }
        });
        jMenu3.add(jmNewsWin);

        jmStocksWin.setText("Stocks Window");
        jmStocksWin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmStocksWinActionPerformed(evt);
            }
        });
        jMenu3.add(jmStocksWin);

        jMenu2.add(jMenu3);

        jmHide.setText("Hide All Windows");
        jmHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmHideActionPerformed(evt);
            }
        });
        jMenu2.add(jmHide);

        jmShow.setText("Show All Windows");
        jmShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmShowActionPerformed(evt);
            }
        });
        jMenu2.add(jmShow);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jlLoaded, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlLoaded, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmStocksWinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmStocksWinActionPerformed
     this.toggleWin(sd);
    }//GEN-LAST:event_jmStocksWinActionPerformed

    private void jmHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmHideActionPerformed
        this.hideWins();
    }//GEN-LAST:event_jmHideActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       this.hideWins();
        StartScreen sscreen = new StartScreen();
       sscreen.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jmCovidWinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCovidWinActionPerformed
      if(cu.isCovid()){
        this.toggleWin(cd);
      }
    }//GEN-LAST:event_jmCovidWinActionPerformed

    private void jmNewsWinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmNewsWinActionPerformed
      if(cu.isNews()){
        this.toggleWin(nd);
      }
    }//GEN-LAST:event_jmNewsWinActionPerformed

    private void jmShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmShowActionPerformed
      if(cu.isStocks()){
        sd.setVisible(true);
        }
        if(cu.isCovid()){
        cd.setVisible(true);
        }
        if(cu.isNews()){
        nd.setVisible(true);
        }
    }//GEN-LAST:event_jmShowActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       System.exit(1);
    }//GEN-LAST:event_jButton1ActionPerformed
    public void toggleWin(JFrame frame){
    frame.setVisible(!frame.isVisible());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoardControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoardControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoardControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoardControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoardControlPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JLabel jlLoaded;
    private javax.swing.JMenuItem jmCovidWin;
    private javax.swing.JMenuItem jmHide;
    private javax.swing.JMenuItem jmNewsWin;
    private javax.swing.JMenuItem jmShow;
    private javax.swing.JMenuItem jmStocksWin;
    private javax.swing.JMenu jmtoMain;
    // End of variables declaration//GEN-END:variables

   
}
